<?php
namespace App\Services;

use App\Core\DB;

/** Creates the database, tables and default data. Used by /install and database/install.php. */
class Installer
{
    public static function createDatabase(string $name): void
    {
        if (!preg_match('/^\w+$/', $name)) throw new \InvalidArgumentException('Database name may only contain letters, numbers and _');
        DB::server()->exec("CREATE DATABASE IF NOT EXISTS `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        DB::reconnect();
    }

    /** Run every statement in database/schema.sql (all CREATE TABLE IF NOT EXISTS, so it is re-runnable). */
    public static function createTables(): void
    {
        foreach (self::statements(file_get_contents(BASE_PATH . '/database/schema.sql')) as $sql) {
            DB::pdo()->exec($sql);
        }
    }

    /** Split a .sql file into statements (statements end with ";" at the end of a line). */
    public static function statements(string $sql): array
    {
        $sql = preg_replace('/^\s*--.*$/m', '', $sql);
        $parts = preg_split('/;\s*(\r?\n|$)/', $sql);
        return array_values(array_filter(array_map('trim', $parts), fn ($s) => $s !== ''));
    }

    public static function install(bool $withSample = true, string $adminPassword = 'admin123', string $adminPin = '1234'): void
    {
        self::createTables();
        Seeder::base($adminPassword, $adminPin);
        Migrations::run();   // marks the database as up to date (and seeds discount presets)
        if ($withSample) Seeder::sample();
    }

    public static function isInstalled(): bool
    {
        try {
            return (bool) DB::value("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = 'users'")
                && (bool) DB::value('SELECT COUNT(*) FROM users');
        } catch (\Throwable $e) {
            return false;
        }
    }

    public static function writeConfig(array $db): void
    {
        $config = [
            'db' => $db,
            'app' => ['timezone' => 'Asia/Manila', 'debug' => false, 'base_path' => config('app.base_path', '')],
        ];
        $php = "<?php\n// Generated by the installer. Edit to change database credentials.\nreturn " . var_export($config, true) . ";\n";
        if (file_put_contents(BASE_PATH . '/config/config.php', $php) === false) {
            throw new \RuntimeException('Could not write config/config.php — check folder permissions.');
        }
    }
}
